Lab 3 Complete
Denchidlo/itddp pull request #2
Opened 2022-05-12 02:25 UTC by Denchidlo

Oh shishh.. Here we go again. 

Here I've prepared some frontend stuff for you (HTML and CSS). Don't be thrown by the commit order here since I've produced deploy branch (smth like dev version) and all future commits would have its origin

2022-05-12 02:27 UTC, Denchidlo commented
Btw see deploy branch to observe results of all of my struggles and sufferings)

2022-05-16 11:43 UTC, katetushkan requested changes

2022-05-16 11:43 UTC, katetushkan commented on studio/projects.html
> +            <div class="menu-header__trigger">
`section` would be better here.

2022-05-16 11:43 UTC, katetushkan commented on studio/projects.html
> +                    <label>AI Studio</label>
`label` can't live without `input`, so go with `<p>`, '<span>', '<strong>' would be correct.

2022-05-16 11:43 UTC, katetushkan commented on studio/projects.html
> +                        <div class="projects-page__card-header">
Maybe, if that's a `-header` , so use `<header>`?)

2022-05-16 11:43 UTC, katetushkan commented on studio/projects.html
> +                        </div>
u can make It `article`.

2022-05-16 11:43 UTC, katetushkan commented on studio/collaborators.html
> +            <div class="overlay-form-user-info__main-content-stat-tasks-completed">
it's better use `<dl>` [tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) for this

2022-05-16 11:43 UTC, katetushkan commented on src/css/forms/common.css
> +.overlayBg {
couldn't find this class in html...(

2022-05-16 11:43 UTC, katetushkan commented on src/css/forms/common.css
> +  width: 100vw;
if u wanna stretch ur element full screen better use % for this, viewport values can be tricky on mobile devices.

2022-05-16 14:16 UTC, Denchidlo commented on src/css/forms/common.css
> +.overlayBg {
Fixed it, u faced it as this class was automatically created during overlay init

2022-05-16 14:16 UTC, Denchidlo commented on src/css/forms/common.css
> +  width: 100vw;
Fixed it, thx a lot!

2022-05-17 12:00 UTC, katetushkan approved these changes
Good. That's <kbd>9</kbd>.

2022-05-17 12:10 UTC, merged